### ISSUE TITLE
Explain why we don't use SERPENT2 built-in reprocessing feature

### ISSUE THREAD

**Issue by andrewryh** [arfc/msbr-reproc#34]
Reviewer 1:
- [x] Page 14, line 234 onwards: Doesn't SERPENT already have an MSR removal capability? If so, what is different about using SaltProc with SERPENT?

Reviewer 2:
- [x] The most critical point of the work is that the built-in capabilities for online reprocessing of Serpent 2 have not been used. Their use is mentioned in the future work, but it is not clear why these capabilities have not been used in the current work. To the author's knowledge, they have been available in Serpent 2 since quite a while. The authors should clarify this point at the beginning of the paper, and not only in the "Future work" section. Even though the technical work was done without using these capabilities, they should highlight what  SaltProc adds to the built-in Serpent capabilities, and they should at least try to extrapolate on the potential advantages of combining  SaltProc and Serpent capabilities. Based on this, they should slightly restructure the paper in order to prove the claimed advantages over Serpent 2.

Reviewer 3:
- [x] 4. In Page 5, the following sentence needs to be explained. "We employed this extended SERPENT 2 for a simplified unit-cell geometry of thermal spectrum thorium-fueled MSBR and obtained results which contradict existing MSBR depletion simulations."

**Comment by katyhuff** [comment]
- state more clearly what disagrees between serpent built-in and previously published results (like, was it compositions, criticaliaty, wrong units/rate of removal, behavior not matching specifications... )
- mention the state of the documentation (missing)
- mention/summarize the conversation on the forum. (e.g. mass conservation checks, type 1,2,3 handling, etc.)
- Are there any publications using this that mention it ---recently--- ??? (if none since manu, note this is indicative of lack of reproducibility)

**Comment by katyhuff** [comment]
closed with #36 #43
